BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/

Include: yum

%help
This is a container to run AMREX binarie on SKL machine. just type ./amrex.img and it should run

%post

        #get binaries and input files
	
	yum install wget -y
        wget https://github.com/Smahane/Intel-HPC-Container/blob/master/containers/amrex/Nyx3d.intel.MPI.OMP.SKLAVX512.ex
	wget https://github.com/Smahane/Intel-HPC-Container/blob/master/containers/amrex/inputs
	
	chmod +x Nyx3d.intel.MPI.OMP.SKLAVX512.ex
	chmod +x inputs
		
	#installing runtime libs for virtual machines
        rpm --import https://yum.repos.intel.com/2018/setup/RPM-GPG-KEY-intel-psxe-runtime-2018
	rpm -Uhv https://yum.repos.intel.com/2018/setup/intel-psxe-runtime-2018-reposetup-1-0.noarch.rpm
	yum install intel-psxe-runtime -y

	#installing gcc
        yum install gcc -y
        yum install bc -y

%environment
#	export OMP_NUM_THREADS=40
	
%runscript 
        echo "This is what happens when you run the container..."
	
	source /opt/intel/psxe_runtime/linux/bin/psxevars.sh
	chmod +x Nyx3d.intel.MPI.OMP.SKLAVX512.ex
	
        result="Nyx3d.intel.MPI.OMP.SKLAVX512.log"
	./Nyx3d.intel.MPI.OMP.SKLAVX512.ex inputs |tee $result
	echo "find results in /tmp/Nyx3d.intel.MPI.OMP.SKLAVX512.ex.log"
